<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<link rel="shortcut icon" href="sites/default/files/cesa.jpg" type="image/jpg" />
<meta name="generator" content="Drupal 7 (http://drupal.org)" />
<link rel="canonical" href="http://fidic.org/" />
<link rel="shortlink" href="http://fidic.org/" />
  <title>CESA| Consulting Engineers South Africa</title>
echo "  <meta name=\"viewport\" content=\"width=1050\">\n";
echo "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n";
echo "  <link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_xE-rWrJf-fncB6ztZfd2huxqgxu4WO-qwma6Xer30m4.css\" media=\"all\" />\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_eZ3p35qbpMElau5YqPT6uqOLsCc1hWBKiKaQN1wwWzk.css\" media=\"screen\" />\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_DjJCxxTEMZCCrGaX6W17F1YFZwfvwjwbw5ZeoS5Jk8k.css\" media=\"all\" />\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_vZ_wrMQ9Og-YPPxa1q4us3N7DsZMJa-14jShHgRoRNo.css\" media=\"screen\" />\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_mhfXY5MXuNaAdfStRCcHBKR4hjBGzHzJlsnbCa3gtr0.css\" media=\"all\" />\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_9s_E7POI7FJZvVfZuk99SDB9B9hXfQj_vTHikzktIy8.css\" media=\"all\" />\n";
echo "<style type=\"text/css\" media=\"all\">\n";
echo "<!--/*--><![CDATA[/*><!--*/\n";
echo ".panels-flexible-new .panels-flexible-region {\n";
echo "  padding: 0;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-region-inside {\n";
echo "  padding-right: 0.5em;\n";
echo "  padding-left: 0.5em;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-region-inside-first {\n";
echo "  padding-left: 0;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-region-inside-last {\n";
echo "  padding-right: 0;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-column {\n";
echo "  padding: 0;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-column-inside {\n";
echo "  padding-right: 0.5em;\n";
echo "  padding-left: 0.5em;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-column-inside-first {\n";
echo "  padding-left: 0;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-column-inside-last {\n";
echo "  padding-right: 0;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-row {\n";
echo "  padding: 0 0 0.5em 0;\n";
echo "  margin: 0;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new .panels-flexible-row-last {\n";
echo "  padding-bottom: 0;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-column-new-main {\n";
echo "  float: left;\n";
echo "  width: 99.0000%;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new-inside {\n";
echo "  padding-right: 0px;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-new {\n";
echo "  width: auto;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-region-new-center {\n";
echo "  float: left;\n";
echo "  width: 99.0000%;\n";
echo "}\n";
echo "\n";
echo ".panels-flexible-row-new-main-row-inside {\n";
echo "  padding-right: 0px;\n";
echo "}\n";
echo "\n";
echo "\n";
echo "/*]]>*/-->\n";
echo "</style>\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_A0cH0vGXV3Mcfks793jqK-E2asd9sKre1gGSQDhxTxA.css\" media=\"all\" />\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/all/modules/features/site_crm/site_crm.css\" media=\"all\" />\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_b3qqzcYiocKia28j4R4fIlR5AhxAuRGYynO2xLpEKt0.css\" media=\"all\" />\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"sites/default/files/css/css_4ctP5w-xk2YhyVvSj9sdFdGH7_jh68JO1ot-v4W-Dx4.css\" media=\"print\" />\n";
echo "\n";
echo "<!--[if lte IE 7]>\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"http://fidic.org/sites/default/files/css/css_yagUuxMDMoO4YrT5NbzfK2LdRHwfVZzaQdHNWa5PFcM.css\" media=\"all\" />\n";
echo "<![endif]-->\n";
echo "\n";
echo "<!--[if lte IE 6]>\n";
echo "<link type=\"text/css\" rel=\"stylesheet\" href=\"http://fidic.org/sites/default/files/css/css_DWk9rnZ_YJ301FXce3FGKgQZL8x98Zm3MYVamlS74qs.css\" media=\"all\" />\n";
echo "<![endif]-->\n";
echo "  <script type=\"text/javascript\" src=\"sites/default/files/js/js_qikmINIYTWe4jcTUn8cKiMr8bmSDiZB9LQqvceZ6wlM.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"sites/default/files/js/js_sDbavFK3G2kbCUumExKmFgXsyD2vAMRcYnSbY519Vcg.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"sites/default/files/js/js_Eitd76bxjZ9igdxkrCgQ8ScGfvlVvLbEAsMMmGoVhWc.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"sites/default/files/js/js_DgOMLrB0OjiCcD2cmT1loWlyilT4kC08zZjnvrF33ac.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"sites/all/modules/custom/site_customizations/js/ie9_compatibility.js?1559625094\"></script>\n";
echo "<script type=\"text/javascript\" src=\"sites/default/files/js/js_ZDn2hZOfsW4kVYj5G7lxSyyVjmlObLH3Ci41G1X4fXc.js\"></script>\n";
echo "<script type=\"text/javascript\">\n";
echo "<!--//--><![CDATA[//><!--\n";
echo "(function(i,s,o,g,r,a,m){i[\"GoogleAnalyticsObject\"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,\"script\",\"//www.google-analytics.com/analytics.js\",\"ga\");ga(\"create\", \"UA-23462730-2\", {\"cookieDomain\":\"auto\"});ga(\"send\", \"pageview\");\n";
echo "//--><!]]>\n";
echo "</script>\n";
echo "<script type=\"text/javascript\" src=\"sites/default/files/js/js_iYOLx_6VbVxAhiHAeItz6jyV9U3wAPfSo9277wRkn6I.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"sites/default/files/js/js_jxhL6plHg5BX3tihEuoFgkgHN2VGdMtFMlOzoVSo7nc.js\"></script>\n";
echo "<script type=\"text/javascript\">\n";
echo "<!--//--><![CDATA[//><!--\n";
echo "(function(i,s,o,g,r,a,m){i[\"GoogleAnalyticsObject\"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,\"script\",\"//www.google-analytics.com/analytics.js\",\"ga\");ga(\"create\", \"UA-23462730-2\", {\"cookieDomain\":\"auto\"});ga(\"send\", \"pageview\");\n";
echo "//--><!]]>\n";
echo "</script>\n";
echo "<script type=\"text/javascript\" src=\"sites/default/files/js/js_kaVdWQJau3u2zY4E4MI-HAvrwgPUr_JeyCIio53O0DE.js\"></script>\n";
echo "<script type=\"text/javascript\" src=\"sites/default/files/js/js_jxhL6plHg5BX3tihEuoFgkgHN2VGdMtFMlOzoVSo7nc.js\"></script>\n";
echo "<script type=\"text/javascript\">\n";
echo "<!--//--><![CDATA[//><!--\n";
echo "jQuery.extend(Drupal.settings, {\"basePath\":\"/\",\"pathPrefix\":\"\",\"ajaxPageState\":{\"theme\":\"fidic\",\"theme_token\":\"zvRdIDXofmXnDRVi_SX5l7Hdmag4pOb--uMRCwKmmFA\",\"js\":{\"misc/jquery.js\":1,\"misc/jquery-extend-3.4.0.js\":1,\"misc/jquery.once.js\":1,\"misc/drupal.js\":1,\"sites/all/modules/contrib/qtip/library/jquery.qtip.js\":1,\"sites/all/modules/contrib/qtip/js/qtip.js\":1,\"sites/all/modules/contrib/visualization/js/visualization.js\":1,\"sites/all/modules/contrib/lightbox2/js/lightbox.js\":1,\"sites/all/modules/custom/site_customizations/js/ie9_compatibility.js\":1,\"sites/all/modules/contrib/google_analytics/googleanalytics.js\":1,\"0\":1,\"sites/all/themes/fidic/js/event-map.js\":1,\"sites/all/themes/fidic/grid/switchgrid.js\":1,\"sites/all/themes/fidic/js/cart_small_tooltip.js\":1},\"css\":{\"modules/system/system.base.css\":1,\"modules/system/system.menus.css\":1,\"modules/system/system.messages.css\":1,\"modules/system/system.theme.css\":1,\"sites/all/modules/contrib/qtip/library/jquery.qtip.css\":1,\"sites/all/modules/contrib/qtip/css/qtip.css\":1,\"modules/comment/comment.css\":1,\"sites/all/modules/contrib/date/date_api/date.css\":1,\"sites/all/modules/contrib/date/date_popup/themes/datepicker.1.7.css\":1,\"sites/all/modules/contrib/date/date_repeat_field/date_repeat_field.css\":1,\"modules/field/theme/field.css\":1,\"modules/node/node.css\":1,\"modules/search/search.css\":1,\"modules/user/user.css\":1,\"sites/all/modules/contrib/workflow/workflow_admin_ui/workflow_admin_ui.css\":1,\"sites/all/modules/contrib/views/css/views.css\":1,\"sites/all/modules/contrib/media/modules/media_wysiwyg/css/media_wysiwyg.base.css\":1,\"sites/all/modules/contrib/ctools/css/ctools.css\":1,\"sites/all/modules/contrib/lightbox2/css/lightbox_alt.css\":1,\"sites/all/modules/contrib/panels/css/panels.css\":1,\"sites/all/modules/contrib/civicrm/css/civicrm.css\":1,\"http://fidic.org/sites/all/modules/features/site_crm/site_crm.css\":1,\"sites/all/modules/contrib/ds/layouts/ds_2col/ds_2col.css\":1,\"sites/all/themes/fidic/css/style.css\":1,\"sites/all/themes/fidic/css/print.css\":1,\"sites/all/themes/fidic/css/ie7.css\":1,\"sites/all/themes/fidic/css/ie6.css\":1}},\"lightbox2\":{\"rtl\":0,\"file_path\":\"/(ww/)public:/\",\"default_image\":\"/sites/all/modules/contrib/lightbox2/images/brokenimage.jpg\",\"border_size\":10,\"font_color\":\"000\",\"box_color\":\"fff\",\"top_position\":\"\",\"overlay_opacity\":\"0.8\",\"overlay_color\":\"000\",\"disable_close_click\":1,\"resize_sequence\":0,\"resize_speed\":400,\"fade_in_speed\":400,\"slide_down_speed\":600,\"use_alt_layout\":1,\"disable_resize\":0,\"disable_zoom\":0,\"force_show_nav\":0,\"show_caption\":1,\"loop_items\":0,\"node_link_text\":\"View Image Details\",\"node_link_target\":0,\"image_count\":\"Image !current of !total\",\"video_count\":\"Video !current of !total\",\"page_count\":\"Page !current of !total\",\"lite_press_x_close\":\"press u003Ca href=u0022#u0022 onclick=u0022hideLightbox(); return FALSE;u0022u003Eu003Ckbdu003Exu003C/kbdu003Eu003C/au003E to close\",\"download_link_text\":\"\",\"enable_login\":false,\"enable_contact\":false,\"keys_close\":\"c x 27\",\"keys_previous\":\"p 37\",\"keys_next\":\"n 39\",\"keys_zoom\":\"z\",\"keys_play_pause\":\"32\",\"display_image_size\":\"original\",\"image_node_sizes\":\"()\",\"trigger_lightbox_classes\":\"\",\"trigger_lightbox_group_classes\":\"\",\"trigger_slideshow_classes\":\"\",\"trigger_lightframe_classes\":\"\",\"trigger_lightframe_group_classes\":\"\",\"custom_class_handler\":0,\"custom_trigger_classes\":\"\",\"disable_for_gallery_lists\":true,\"disable_for_acidfree_gallery_lists\":true,\"enable_acidfree_videos\":true,\"slideshow_interval\":5000,\"slideshow_automatic_start\":true,\"slideshow_automatic_exit\":true,\"show_play_pause\":true,\"pause_on_next_click\":false,\"pause_on_previous_click\":true,\"loop_slides\":false,\"iframe_width\":1024,\"iframe_height\":600,\"iframe_border\":1,\"enable_video\":0,\"useragent\":\"CyotekWebCopy/1.7 CyotekHTTP/2.0\"},\"qtip\":{\"target_position\":\"top_right\",\"tooltip_position\":\"bottom_left\",\"show_speech_bubble_tip\":true,\"show_speech_bubble_tip_side\":false,\"speech_bubble_size\":12,\"show_speech_bubble_tip_solid\":false,\"show_shadow\":false,\"rounded_corners\":false,\"color\":\"\",\"custom_color\":\"\",\"show_event_type\":\"mouseenter\",\"hide_event_type\":\"mouseleave\",\"show_webform_descriptions\":false,\"additional_elements\":\"\"},\"urlIsAjaxTrusted\":{\"/search\":true},\"googleanalytics\":{\"trackOutbound\":1,\"trackMailto\":1,\"trackDownload\":1,\"trackDownloadExtensions\":\"7z|aac|arc|arj|asf|asx|avi|bin|csv|doc(x|m)?|dot(x|m)?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|sld(x|m)?|thmx|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip\"}});\n";
echo "//--><!]]>      \n";
echo "</script>\n";
echo "</head>\n";
echo "<body class=\"html front not-logged-in no-sidebars page-homepage page-panels\" >\n";
echo "      <div id=\"skip-link\">\n";
echo "      <a href=\"#main-menu\" class=\"element-invisible element-focusable\">Jump to navigation</a>\n";
echo "    </div>\n";
echo "      \n";
echo "<div id=\"page-wrapper\">\n";
echo "  <div id=\"header\">\n";
echo "  <div class=\"header-wrap container clearfix\">\n";
echo "\n";
echo "      <div id=\"logo-container\" class=\"grid-10\">\n";
echo "                  <a href=\"/\" title=\"Home\" rel=\"home\" id=\"logo\">\n";
echo "                        <img src=\"sites/all/themes/cesa/images/logo.jpg\" alt=\"Home\"/>\n";
echo "          </a>\n";
echo "              </div>\n";
echo "      \n";
echo "      <div class=\"header-region clearfix\">\n";
echo "        <div class =\"pngcontainer2\">\n";
echo "       <img src=\"sites/all/themes/cesa/images/bkg-02.png\"/>\n";
echo "      </div>\n";
echo "          <div class=\"region region-header\">\n";
echo "    <div id=\"block-site-customizations-header-login\" class=\"block block-site-customizations first odd\">\n";
echo "\n";
echo "      \n";
echo "  <div class=\"content\">\n";
echo "    <ul class=\"menu\"><li class=\"login leaf first last\"><a href=\"/user\">MEMBER LOGIN</a></li>\n";
echo "</ul>  </div>\n";
echo "\n";
echo "</div><!-- /.block -->\n";
echo "<div id=\"block-views-shopping-cart-items-block-1\" class=\"block block-views last even\">\n";
echo "\n";
echo "      \n";
echo "  <div class=\"content\">\n";
echo "    <div class=\"view view-shopping-cart-items view-id-shopping_cart_items view-display-id-block_1 view-dom-id-a6eb4c6cc38d28001307b3f1fdb0673d\">\n";
echo "        \n";
echo "  \n";
echo "  \n";
echo "      <div class=\"view-empty\">\n";
echo "      <a class=\"phone\" href=\"/basket\">CONTACT US</a>     </div>\n";
echo "       <div class=\"search-region clearfix\">\n";
echo "            <div class=\"region region-search\">\n";
echo "    <div id=\"block-views-exp-search-page-1\" class=\"block block-views first last odd\">\n";
echo "\n";
echo "      \n";
echo "  <div class=\"wrapper\">\n";
echo "  <div class=\"search-container\">\n";
echo "    <a href=\"#/search\" class=\"search-button\">\n";
echo "      <i class=\"fa fa-search\"></i>\n";
echo "    </a>\n";
echo "    <input type=\"text\" placeholder=\"Search\">\n";
echo "  </div>\n";
echo "  \n";
echo "</div>\n";
echo "\n";
echo "</div><!-- /.block -->\n";
echo "  </div><!-- /.region -->\n";
echo "        </div>\n";
echo "  \n";
echo "  \n";
echo "  \n";
echo "  \n";
echo "  \n";
echo "</div>  </div>\n";
echo "\n";
echo "</div><!-- /.block -->\n";
echo "  </div><!-- /.region -->\n";
echo "      </div>\n";
echo "\n";
echo "    <div class=\"navigation clearfix\">\n";
echo "\n";
echo "      <div class=\"content\">\n";
echo "          <div class=\"region region-navigation\">\n";
echo "    <div id=\"block-menu-block-4\" class=\"block block-menu-block first last odd\">\n";
echo "\n";
echo "      \n";
echo "  <div class=\"content\">\n";
echo "    <div class=\"menu-block-wrapper menu-block-4 menu-name-main-menu parent-mlid-0 menu-level-1\">\n";
echo "  <ul class=\"menu\"><li class=\"first leaf active menu-mlid-227\"><a href=\"index.htm\" class=\"active\">Home</a></li>\n";
echo "<li class=\"expanded menu-mlid-20888\"><a href=\"about_us.htm\" class=\"has-submenu\">About Us</a><ul class=\"menu\"><li class=\"first expanded menu-mlid-33800\"><a href=\"about_cesa.htm\" title=\"\" class=\"has-submenu\">About Cesa</a><ul class=\"menu\">\n";
echo "</ul></li>\n";
echo "<li class=\"leaf menu-mlid-10141\"><a href=\"board.htm\">Board</a></li>\n";
echo "<li class=\"leaf menu-mlid-10155\"><a href=\"cesa_staff.htm\">CESA Staff</a></li>\n";
echo "<li class=\"leaf menu-mlid-10169\"><a href=\"member_firms.htm\">Member Firms</a></li>\n";
echo "<li class=\"leaf menu-mlid-10151\"><a href=\"cesa_committees.htm\">CESA Committees</a></li>\n";
echo "<li class=\"expanded menu-mlid-21440\"><a href=\"ypf.htm\" class=\"has-submenu\">YPF</a><ul class=\"menu\">\n";
echo "</ul></li>\n";
echo "<li class=\"last leaf menu-mlid-40314\"><a href=\"/node/10134\">Contact Us</a></li>\n";
echo "</ul></li>\n";
echo "<li class=\"expanded menu-mlid-3116\"><a href=\"cesa_member.htm\" class=\"has-submenu\">Membership</a><ul class=\"menu\"><li class=\"first leaf menu-mlid-23476\"><a href=\"cesa_member.htm\" title=\"\">Why Become a Cesa Member</a></li>\n";
echo "<li class=\"leaf menu-mlid-3117\"><a href=\"cesa_directory.htm\">Cesa Directory</a></li>\n";
echo "<li class=\"leaf menu-mlid-5409\"><a href=\"benefits.htm\">Benefits of Cesa Members</a></li>\n";
echo "<li class=\"last expanded menu-mlid-3849\"><a href=\"affiliates.htm\" class=\"has-submenu\">Affiliate Partners</a><ul class=\"menu\"><li class=\"first leaf menu-mlid-3850\"><a href=\"affiliate_benefits.htm\">Benefits of becoming an affiliate</a></li>\n";
echo "</ul></li>\n";
echo "</ul></li>\n";
echo "<li class=\"expanded menu-mlid-3098\"><a href=\"procurement.htm\" class=\"has-submenu\">Advocacy</a><ul class=\"menu\"><li class=\"first leaf menu-mlid-23477\"><a href=\"procurement.htm\" title=\"\">Procurement</a></li>\n";
echo "<li class=\"leaf menu-mlid-5408\"><a href=\"member_archives.htm\" title=\"Complete list of current events\">What we are Archiving for our members</a></li>\n";
echo "<li class=\"leaf menu-mlid-2951\"><a href=\"partnerships.htm\">Partnerships</a></li>\n";
echo "</ul></li>\n";
echo "<li class=\"expanded menu-mlid-26363\"><a href=\"infrastructure_indaba.htm\" title=\"Other FIDIC Resources\" class=\"has-submenu\">Events</a><ul class=\"menu\"><li class=\"first leaf menu-mlid-26364\"><a href=\"infrastructure_indaba.htm\">Infrastructure Indaba</a></li>\n";
echo "<li class=\"leaf menu-mlid-26365\"><a href=\"presidential_visits.htm\">Presidential Visits</a></li>\n";
echo "<li class=\"leaf menu-mlid-26366\"><a href=\"cesa_aon.htm\">CESA Aon Awards</a></li>\n";
echo "<li class=\"leaf menu-mlid-26370\"><a href=\"cesa_relay.htm\">CESA Relay</a></li>\n";
echo "<li class=\"leaf menu-mlid-26369\"><a href=\"golf_day.htm\">Golf Day</a></li>\n";
echo "<li class=\"leaf menu-mlid-27882\"><a href=\"AGM.htm\" title=\"\">AGM</a></li>\n";
echo "<li class=\"leaf menu-mlid-27883\"><a href=\"job_shadow.htm\">Job Shadow</a></li>\n";
echo "<li class=\"leaf menu-mlid-26368\"><a href=\"imbizo.htm\" title=\"\">Imbizo</a></li>\n";
echo "</ul></li>\n";
echo "<li class=\"last expanded menu-mlid-39823\"><a href=\"media.htm\" title=\"\" class=\"has-submenu\">Publications</a><ul class=\"menu\"><li class=\"first leaf menu-mlid-41792\"><a href=\"media.htm\" title=\"\">Media</a></li>\n";
echo "<li class=\"leaf menu-mlid-41791\"><a href=\"cesa_publications.htm\" title=\"\">CESA Publication</a></li>\n";
echo "<li class=\"last leaf menu-mlid-45973\"><a href=\"bookshop_documents.htm\">Bookshop Documents </a></li>\n";
echo "<li class=\"last leaf menu-mlid-45973\"><a href=\"cesa_media_release.htm\">CESA Media Release </a></li>\n";
echo "<li class=\"last leaf menu-mlid-45973\"><a href=\"becs.htm\">BEPEC </a></li>\n";
echo "</ul></li>\n";
echo "</ul></div>\n";
echo "  </div>\n";
echo "\n";
echo "</div><!-- /.block -->\n";
echo "  </div><!-- /.region -->\n";
echo "           \n";
echo "              </div>\n";
echo "    </div>\n";
echo "  </div>\n";
echo "</div>\n";
echo "  \n";
echo "      <div id=\"banner\">\n";
echo "    <div class=\"section inner clearfix\">\n";
echo "                <div class=\"region region-banner\">\n";
echo "    <div id=\"block-views-front-home-slideshow-block\" class=\"block block-views first last odd\">\n";
echo "\n";
echo "      \n";
echo "  <div class=\"content\">\n";
echo "    <div class=\"view view-front-home-slideshow view-id-front_home_slideshow view-display-id-block view-dom-id-97a5cb821a85fde3bf22c8a9523bf78f\">\n";
echo "        \n";
echo "  \n";
echo "  \n";
echo "      <div class=\"view-content\">\n";
echo "      \n";
echo "  <div class=\"skin-default\">\n";
echo "    \n";
echo "    <div id=\"views_slideshow_cycle_main_front_home_slideshow-block\" class=\"views_slideshow_cycle_main views_slideshow_main\"><div id=\"views_slideshow_cycle_teaser_section_front_home_slideshow-block\" class=\"views-slideshow-cycle-main-frame views_slideshow_cycle_teaser_section\">\n";
echo "  <div id=\"views_slideshow_cycle_div_front_home_slideshow-block_0\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-1 views-row-odd\">\n";
echo "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-0 views-row-odd views-row-first\">\n";
echo "    \n";
echo "  <div class=\"views-field views-field-field-front-image\">        <div class=\"field-content\"><a href=\"http://fidic.org/node/22751\"><img src=\"images/slider.jpg\" width=\"1024\" height=\"259\" /></a></div>  </div></div>\n";
echo "</div>\n";
echo "<div id=\"views_slideshow_cycle_div_front_home_slideshow-block_1\" class=\"views-slideshow-cycle-main-frame-row views_slideshow_cycle_slide views_slideshow_slide views-row-2 views_slideshow_cycle_hidden views-row-even\">\n";
echo "  <div class=\"views-slideshow-cycle-main-frame-row-item views-row views-row-1 views-row-even\">\n";
echo "    \n";
echo "  <div class=\"views-field views-field-field-front-image\">        <div class=\"field-content\"><a href=\"http://fidic2019.org/en\"><img src=\"images/slider-2.jpg\" /></a></div>  </div></div>\n";
echo "</div>\n";
echo "\n";
echo "</div>\n";
echo "</div>\n";
echo "      </div>\n";
echo "    </div>\n";
echo "  \n";
echo "</div>  </div>\n";
echo "\n";
echo "</div><!-- /.block -->\n";
echo "  </div><!-- /.region -->\n";
echo "          </div>\n";
echo "</div>";
<body>
</body>
</html>